export default {
  'allContent---dsg-website-docs-docusaurus-debug-content-246-c80': [() => import(/* webpackChunkName: 'allContent---dsg-website-docs-docusaurus-debug-content-246-c80' */ "~debug/default/docusaurus-debug-all-content-673.json"), "~debug/default/docusaurus-debug-all-content-673.json", require.resolveWeak("~debug/default/docusaurus-debug-all-content-673.json")],
  'component---theme-debug-config-23-a-2ff': [() => import(/* webpackChunkName: 'component---theme-debug-config-23-a-2ff' */ "@theme/DebugConfig"), "@theme/DebugConfig", require.resolveWeak("@theme/DebugConfig")],
  'component---theme-debug-contentba-8-ce7': [() => import(/* webpackChunkName: 'component---theme-debug-contentba-8-ce7' */ "@theme/DebugContent"), "@theme/DebugContent", require.resolveWeak("@theme/DebugContent")],
  'component---theme-debug-global-dataede-0fa': [() => import(/* webpackChunkName: 'component---theme-debug-global-dataede-0fa' */ "@theme/DebugGlobalData"), "@theme/DebugGlobalData", require.resolveWeak("@theme/DebugGlobalData")],
  'component---theme-debug-registry-679-501': [() => import(/* webpackChunkName: 'component---theme-debug-registry-679-501' */ "@theme/DebugRegistry"), "@theme/DebugRegistry", require.resolveWeak("@theme/DebugRegistry")],
  'component---theme-debug-routes-946-699': [() => import(/* webpackChunkName: 'component---theme-debug-routes-946-699' */ "@theme/DebugRoutes"), "@theme/DebugRoutes", require.resolveWeak("@theme/DebugRoutes")],
  'component---theme-debug-site-metadata-68-e-3d4': [() => import(/* webpackChunkName: 'component---theme-debug-site-metadata-68-e-3d4' */ "@theme/DebugSiteMetadata"), "@theme/DebugSiteMetadata", require.resolveWeak("@theme/DebugSiteMetadata")],
  'component---theme-doc-item-178-a40': [() => import(/* webpackChunkName: 'component---theme-doc-item-178-a40' */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  'component---theme-doc-page-1-be-9be': [() => import(/* webpackChunkName: 'component---theme-doc-page-1-be-9be' */ "@theme/DocPage"), "@theme/DocPage", require.resolveWeak("@theme/DocPage")],
  'content---dsg-website-docs-c-37-c78': [() => import(/* webpackChunkName: 'content---dsg-website-docs-c-37-c78' */ "@site/docs/index.md"), "@site/docs/index.md", require.resolveWeak("@site/docs/index.md")],
  'content---dsg-website-docs-partner-logos-947-919': [() => import(/* webpackChunkName: 'content---dsg-website-docs-partner-logos-947-919' */ "@site/docs/partner_logos.md"), "@site/docs/partner_logos.md", require.resolveWeak("@site/docs/partner_logos.md")],
  'versionMetadata---dsg-website-docs-935-58b': [() => import(/* webpackChunkName: 'versionMetadata---dsg-website-docs-935-58b' */ "~docs/default/version-current-metadata-prop-751.json"), "~docs/default/version-current-metadata-prop-751.json", require.resolveWeak("~docs/default/version-current-metadata-prop-751.json")],};
